name: Build All Platforms

on:
  push:
    branches: [ main, cursor/update-upload-artifact-action-to-v4-9c37 ]
  pull_request:
    branches: [ main, cursor/update-upload-artifact-action-to-v4-9c37 ]
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    name: Build Android
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Create app icon
      run: flutter pub run flutter_launcher_icons:main
      
    - name: Build APK
      run: flutter build apk --release
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        
    - name: Build App Bundle
      run: flutter build appbundle --release
      
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: app-release-aab
        path: build/app/outputs/bundle/release/app-release.aab

  web:
    runs-on: ubuntu-latest
    name: Build Web
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Build Web
      run: flutter build web --release
      
    - name: Upload Web build
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: build/web/

  ios:
    runs-on: macos-latest
    name: Build iOS
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Create app icon
      run: flutter pub run flutter_launcher_icons:main
      
    - name: Build iOS
      run: flutter build ios --release --no-codesign
      
    - name: Upload iOS build
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: build/ios/iphoneos/

  windows:
    runs-on: windows-latest
    name: Build Windows
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Build Windows
      run: flutter build windows --release
      
    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: build/windows/runner/Release/

  linux:
    runs-on: ubuntu-latest
    name: Build Linux
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build clang libgtk-3-dev
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Build Linux
      run: flutter build linux --release
      
    - name: Upload Linux build
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: build/linux/x64/release/bundle/